import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import { ProductList } from "../components/ProductList";
import { getAllProducts } from "../services/data/product-endpoint";
import { TProduct } from "../mocks/products";

import 'react-loading-skeleton/dist/skeleton.css'

const Home: NextPage = () => {
  const [productsList, setProductsList] = useState([] as TProduct[]);
  const [isLoading, setIsLoading] = useState(true);

  const hasProducts = productsList.length > 0;

  function changeLoadingTime() {
    setTimeout(() => {
      setIsLoading(false);
    }, 2000);
  }

  async function getProductsList() {
    const { data: ProductList } = await getAllProducts();

    setProductsList(ProductList);
  }
  useEffect(() => {
    getProductsList();
    changeLoadingTime();
  }, []);
  return (
    <>
      <Head>
        <title>ShoppingProJX | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <div className="contentContainer">
          <ul>
            {hasProducts && (
              <ProductList products={productsList} isLoading={isLoading} />
            )}
          </ul>
        </div>
      </main>
    </>
  );
};

export default Home;
